security:
    providers:
        db_provider:
            entity:
                class:      App\Entity\User
                property:   username
    encoders:
        App\Entity\User:
          algorithm:        bcrypt
          cost:             12
    firewalls:
        dev:
            pattern:        ^/(_(profiler|wdt)|css|images|js)/
            security:       false
        main:
            pattern:        ^/
            anonymous:      ~
            provider:       db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:       logout
                target:     /
            user_checker:   App\Security\UserChecker
            remember_me:
              secret:       '%kernel.secret%'
